name: VersionTagger
on:
  [workflow_dispatch, repository_dispatch, push]
jobs:
  TagRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Release
        id: "check_release"
        run: |
          STR=$(curl -s  https://api.github.com/repos/boecker-lab/sirius/releases | grep 'browser_download_url.*linux64-service.zip\"' | sort | tac | head -n 1)
          SUB="SNAPSHOT"
          VER=$([[ $STR =~ (v[0-9].[0-9].[0-9]) ]] && echo ${BASH_REMATCH[1]})
          echo "STR=$STR" >> $GITHUB_OUTPUT
          echo "SUB=$SUB" >> $GITHUB_OUTPUT
          echo "VER=$VER" >> $GITHUB_OUTPUT
          
      - name: Check Release
        run: |
          echo $STR
          if [[ "${{steps.check_release.outputs.STR}}" == *"${{steps.check_release.outputs.SUB}}"* ]]; then exit 0; fi
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{steps.check_release.outputs.VER}}
          tag_exists_error: true
          
