name: VersionTagger
on:
  [workflow_dispatch, repository_dispatch, push]
jobs:
  TagRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Release
        id: "check_release"
        run: |
          x=$(cat .updater/api/api-docs.json)
          VER=$([[ $x =~ \"version\":\"([0-9].[0-9]) ]] && echo ${BASH_REMATCH[1]})
          echo "VER=$VER" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{steps.check_release.outputs.VER}}
          tag_exists_error: false
          message: "Version: ${{steps.check_release.outputs.VER}}"
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
