name: VersionTagger
on:
  [workflow_dispatch, repository_dispatch, push]
jobs:
  TagRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Release
        run: |
          STR=$(curl -s  https://api.github.com/repos/boecker-lab/sirius/releases | grep 'browser_download_url.*linux64-service.zip\"' | sort | tac | head -n 1)
          SUB="SNAPSHOT"
          VER=$([[ $STR =~ (v[0-9].[0-9].[0-9]) ]] && echo ${BASH_REMATCH[1]})
      - name: Check Release
        run: |
          echo $STR
          if [[ "$STR" == *"$SUB"* ]]; then exit 0; fi
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: $VER
          tag_exists_error: true
          
